### ISSUE TITLE
SCL/SDA Inputs

### ISSUE THREAD

**Issue by maacoba** [xpress-embedo/OLED#1]
Hi, 

My PIC has RC3 and RC4 as SCL/SDA inputs - where do i change this in the I2C code, besides changing the TRIS?

Thank you!

**Comment by xpress-embedo** [comment]
There is a separate submodule for I2C which is used along with this submodule.
And you can update the initialization function ```I2C_Init``` as per your micro-controller.
The following is the path to the submodule.
https://github.com/xpress-embedo/I2C
