### ISSUE TITLE
fonts , how to make?

### ISSUE THREAD

**Issue by floydhaynes** [xpress-embedo/OLED#2]
hello 

How did you make fonts for this  ?
how would I make a 32by16 font ?

regards

**Comment by xpress-embedo** [comment]
Hello
This library is prepared by taking reference from the "Rinky-Dink Electronics" OLED_I2C Library for Arduino.
So, the fonts can also be taken from there and it will work. You can check the below link.
http://www.rinkydinkelectronics.com/r_fonts.php
This will work fine.
Thanks
